storeItemList:
  - id: '16999772985330.11278241433058067'
    name: bucketName
    value: uibakery-sample-bucket
    valueType: string
    initialValue: uibakery-sample-bucket
    version: 1
  - id: '17001359826560.5666104975840678'
    name: searchProgress
    value: 0
    valueType: number
    initialValue: 0
    version: 1
    parentPageId: '17000773280870.8041752909034596'
metadata:
  favicon: ''
  code: |-
    <script>
      function formatBytes(bytes, decimals = 0) {
        bytes = Number(bytes);

        if (!bytes) {
          return "0 bytes";
        }

        // https://en.wikipedia.org/wiki/Binary_prefix
        const units = ["bytes", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB", "RB", "QB"];

        const power = Math.floor(Math.log2(bytes) / 10);

        const number = (bytes / (2 ** 10) ** power).toFixed(decimals);

        const unit = units[power] ?? `* 1024^${power} bytes`;

        return `${number} ${unit}`;
      }

      function encodeHTML(source) {
        return source.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
      }
    </script>
  title: New app
  description: ''
  breakpoints: []
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
  density: compact
internalType: project
